FROM oscarlevin/pretext:lite


RUN apt update && apt install -y --no-install-recommends \
    texlive \
    texlive-plain-generic \
    texlive-science \
    texlive-xetex \
    texlive-fonts-extra \
    ghostscript \
    pdf2svg 
